server:
  port:
    8765

spring:
  application:
    name: zuul-server
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  prefix: /api
  routes:
    user:
      path: /user/**
      serviceId: user-service
    game:
      path: /game/**
      serviceId: games-service
    account:
      path: /account/**
      serviceId: payment-service
    bought:
      path: /bought/**
      serviceId: bought-service
      
user:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    
game:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    
account:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    
bought:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    