spring:
  application:
    name: ribbon-client

server:
  port: 8888
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

user-service:
  ribbon:
    eureka:
      enabled: true
      ReadTimeout: 20000
    ServerListRefreshInterval: 60000
    
payment-service:
  ribbon:
    eureka:
      enabled: true
      ReadTimeout: 20000
    ServerListRefreshInterval: 2000
    
games-service:
  ribbon:
    eureka:
      enabled: true
      ReadTimeout: 20000
    ServerListRefreshInterval: 2000
    
bought-service:
  ribbon:
    eureka:
      enabled: true
      ReadTimeout: 20000
    ServerListRefreshInterval: 2000
    