spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microapp
    username: root
    password: root
    dbcp2:
      test-while-idle: true
      validationQuery: SELECT 1
      
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect        
  application:
    name: games-service
server:
  port: 8081
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/